---
title: "Model Parameters"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Model_Parameters}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## 1. Functions

### 1.1 `coxtp`:

`coxtp(event,z,time,strata=c(),spline="P-spline", nsplines=8, ties="Breslow",tol=1e-9, iter.max=20L, method="Newton",`
`lambda=1e8,factor=10, btr="dynamic", sigma=1e-2, tau=0.6,stop="incre", parallel=FALSE, threads=1L,`
`degree=3L, TIC = FALSE, TIC_prox = FALSE, lambda_spline = 0, ord = 4, fixedstep = FALSE, effectsize = 0,`
`difflambda = FALSE,addsecond = FALSE, penalizestop = FALSE, ICLastOnly = FALSE)`

The main function in our package is `coxtp` which refers to the "Cox Non-proportional Hazards model with penalization". 



#### 1.1.1 Common Parameters

`coxtp` function have two required input, which is `formula` and `data`.

* **`event`**: Event vector, should be a vector containing 0 or 1
* **`z`**: Covariate matrix
* **`time`**: Time vector, should be a vector with non-negative numeric value 
* **`strata`**: stratification group defined in the data. If there exist stratification group, please enter as vector.


#### 1.1.2 Method related Parameters:

Here we offered both model estimation with penalization and without penalization. Detail method could be found in our paper(add link here). Following parameters defines the model settings:

* **`spline`**: The spline term for Penalized Newton's Method(Add section Number related to the paper). Default setting is **`spline="Smooth-spline"`**
  * **`"P-spline"`**: The P-splines are low rank smoother using a B-spline basis. Detail information about P-spline could be found in (Add section number and link)
  * **`"Smooth-spline"`** : (Add section number and link)
* **`nsplines`** : Number of base functions in the B-splines, default is 8.

* **`method`** : Selecting Method used, default is **`method="Newton"`**
  * **`"Newton"`**: Usual Newton’s Approach.
  * **`"ProxN"`** : Proximal Newton–Raphson Method proposed in our paper(get link here).
* **`lambda`** : Parameter for Proximal Newton's Method. Default is **`lambda=1e8`**
* **`tau`** : (Alpha or beta?) in the Newton's Method, Default is **`tau=0.5`**. Used to control for step size.
* **`lambda_spline`** :  Smoothing parameter lambda. Default is **`lambda_spline = 0`** which refers to Newton's Method without penalization.

* **`degree`**: Degree of smoothing spline. Default setting is **`degree=3L`**.
  * **`degree=2L`** refers to Smoothing quadratic spline.
  * **`degree=3L`** refers to Smoothing cubic spline.
  
* **`ord`** : Specify which derivative to penalize. Default setting is **`ord=4`**.
  * **`ord=4`**: Penalized second order derivative, suggest to use this when using the smoothing cubic spline.
  * **`ord=3`**: Penalized first order derivative, suggest to use this when using the smoothing quadratic spline.
  
* `penalizestop`: could delete
  
#### 1.1.3 Stopping creteria related Parameters:

* **`tol`**: Convergence threshold. The default threshold is set as **`tol=1e-6`**
* **`iter.max`**: Maximum Iteration number, default is **`iter.max=20L`**
* **`stop`**: Stopping rule, default is **`stop="ratch"`**:
  * **`incre`**: We define $(l^{(m)}-l^{(m-1)})/(l^{(m)}-l^{(0)})$ as the relative change of the log-partial likelihood, where m denotes the mth step of the algorithm. When it’s smaller than a certain threshold, we stop the algorithm. tol is the variable determining the convergence threshold. 
  * **`relch`**: We define the relative change of the log-partial likelihood as $(l^{(m)}-l^{(m-1)})/(l^{(m)})$, which makes it easier to converge. 
  * **`incre`**: This method would stop the algorithm when the half of the Newton increment is less than the threshold(`tol` defined in the previous argument?? correct??).

* **`fixedstep`**: There might be times when the stopping criteria not working, thus, the number of steps could be set manually. Default value is **`fixedstep = FALSE`**, if it is true, will stop by `iter.max`

#### 1.1.4 Other Parameters:

* **`ties`**: Ways to deal with ties, default is **`ties="Breslow"`**:
  * **`"Breslow"`**: Breslow approximation. Detailed information could be found here(add link)
  * **`"none`**: Don't deal with ties
  
* **`btr`**: Backtracking line search approach, default is `btr="static"`:
  * **`"none"`**: Don't do Backtracking Linesearch.
  * **`"static"`** : When binary predictors with extremely low frequency are present, calculation of the second order derivative has some issues. In that case, the Newton increment presents extreme values, leading to huge bias. We provided a way of limiting the step size in such cases. Instead of using the Newton increment, we use a fixed value of 1. This method is referred as “static” in our function. Since it moves slower, usually it can not achieve maximum likelihood estimator, leading to biased estimation.
  * **`"dynamic"`** : Backtracking Linesearch with Newton Increment. Detail information could be found at(Add link) 

* **`parallel`**: Parallel computation, Default is **`parallel=FALSE`**
* **`threads`** : Parallel computation parameter(number of cores)Default is **`threads=1L`**
* **`TIC_prox`** : When calculating information criteria, there might be numerical issue(second order derivative, Hessian matrix approximate is singular), thus we proposed to add a small term to the diagonal. Default **`TIC_prox = FALSE`**
* **`ICLastOnly`** : Only calculate the last information criteria if is TRUE. Default is **`ICLastOnly=FALSE`**


### 1.2. coxtp.plot

`coxtp.plot(fit,IC="AIC",coef,xlab="Time",ylab="Hazard Ratio (log-scale)")`

Function `coxtp.plot` was created to generate related hazard ratio plot from the result generated from `coxtp`

* **`fit`**: Model fitted from coxtp
* **`IC`** :The Criteria selected for the plotting. Default is IC="AIC".
  * **`IC`**="TIC":  Takeuchi information criterion (Insert link here)
  * **`IC`**="GIC":  Generalized information criterion (Insert link here)
  * **`IC`**="AIC": Akakia information criterion (Insert link here)
* **`coef`**: The variable that needed to be plotted
* **`xlab`**: X axis label, default is xlab="Time"
* **`ylab`**: X axis label, default is ylab="Hazard Ratio (log-scale)"

### 1.3. coxtp.baseline

`coxtp.baseline(fit, delta,z,time,strata=c())`

* **`fit`**: Model fitted from coxtp
* **`delta`**:  Event vector, should be a vector containing 0 or 1
* **`z`**:  Covariate matrix
* **`time`**:  Time vector, should be a vector with non-negative numeric value.
* **`strata`**: stratification group defined in the data. If there exist stratification group, please enter as vector.

### 1.4 coxtp.predict

`coxtp.predict(fit,baseline,newdata=c(),strata=FALSE)`

* **`fit`**: Model get from coxtp
* **`baseline`**: Baseline estimation from coxtp.baseline or the arbitary baseline entered
* **`newdata`**: New data in vector
* **`strata`**: Whether there is stratification in the dataset, default is FALSE.

## 2. Data sets

### 2.1 sim_data

Example data for surtvep with 5000 observations of 4 variables

* **`V1`**: Simulated covariate V1, Binary variable with 0, 1. True time-dependent function is $\beta(t)=1$
* **`V2`**: Simulated covariate V2, Binary variable with 0, 1. True time-dependent function is $\beta(t)=exp(-1.5*t)$
* **`event`**: Simulated event variable, Binary varible with 0, 1 
* **`time`**: Simulated time variable, Continous variable with non-negative value


### 2.2 sim_data_p5

Example data for surtvep with 5000 observations of 7 variables:

* **`V1`**: Simulated covariate V1, Binary variable with 0, 1. True time-dependent function is $\beta(t)=1$
* **`V2`**: Simulated covariate V2, Binary variable with 0, 1. True time-dependent function is $\beta(t)=sin(3\pi t/4)$
* **`V3`**: Simulated covariate V2, Binary variable with 0, 1. True time-dependent function is $\beta(t)=-1$
* **`V4`**: Simulated covariate V2, Binary variable with 0, 1. True time-dependent function is $\beta(t)=(t/3)**2exp(t/2)$
* **`V5`**: Simulated covariate V2, Binary variable with 0, 1. True time-dependent function is $\beta(t)=exp(-1.5t)$
* **`event`**: Simulated event variable, Binary varible with 0, 1 }
* **`time`**: Simulated time variable, Continous variable with non-negative value}


### 2.3 sim_data_p5_f5

Example data for surtvep with 5000 observations of 8 variables(With strata):


* **`V1`**: Simulated covariate V1, Binary variable with 0, 1. True time-dependent function is $\beta(t)=1$
* **`V2`**: Simulated covariate V2, Binary variable with 0, 1. True time-dependent function is $\beta(t)=sin(3\pi t/4)$
* **`V3`**: Simulated covariate V2, Binary variable with 0, 1. True time-dependent function is $\beta(t)=-1$
* **`V4`**: Simulated covariate V2, Binary variable with 0, 1. True time-dependent function is $\beta(t)=(t/3)**2exp(t/2)$
* **`V5`**: Simulated covariate V2, Binary variable with 0, 1. True time-dependent function is $\beta(t)=exp(-1.5t)$
* **`event`**: Simulated event variable, Binary variable with 0, 1 
* **`time`**: Simulated time variable, Continuous variable with non-negative value
* **`facility`**: Simulated stratification variable. Have 5 levels


