# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stra_sampling_cpp <- function(size, prop) {
    .Call(`_surtvep_stra_sampling_cpp`, size, prop)
}

surtiver_fixtra_fit_penalizestop <- function(event, count_strata, Z_tv, B_spline, theta_init, Z_ti, beta_ti_init, lambda_spline, SmoothMatrix, effectsize, SplineType = "pspline", method = "Newton", lambda = 1e8, factor = 1.0, parallel = FALSE, threads = 1L, tol = 1e-10, iter_max = 20L, s = 1e-2, t = 0.6, btr = "dynamic", stop = "incre", TIC_prox = FALSE, fixedstep = TRUE, difflambda = FALSE, ICLastOnly = FALSE) {
    .Call(`_surtvep_surtiver_fixtra_fit_penalizestop`, event, count_strata, Z_tv, B_spline, theta_init, Z_ti, beta_ti_init, lambda_spline, SmoothMatrix, effectsize, SplineType, method, lambda, factor, parallel, threads, tol, iter_max, s, t, btr, stop, TIC_prox, fixedstep, difflambda, ICLastOnly)
}

surtiver_fixtra_fit_penalizestop_bresties <- function(event, time, count_strata, Z_tv, B_spline, theta_init, Z_ti, beta_ti_init, lambda_spline, SmoothMatrix, effectsize, SplineType = "pspline", method = "Newton", lambda = 1e8, factor = 1.0, parallel = FALSE, threads = 1L, tol = 1e-10, iter_max = 20L, s = 1e-2, t = 0.6, btr = "dynamic", stop = "incre", TIC_prox = FALSE, fixedstep = TRUE, difflambda = FALSE, ICLastOnly = FALSE) {
    .Call(`_surtvep_surtiver_fixtra_fit_penalizestop_bresties`, event, time, count_strata, Z_tv, B_spline, theta_init, Z_ti, beta_ti_init, lambda_spline, SmoothMatrix, effectsize, SplineType, method, lambda, factor, parallel, threads, tol, iter_max, s, t, btr, stop, TIC_prox, fixedstep, difflambda, ICLastOnly)
}

LogPartialTest <- function(event, Z_tv, B_spline, event_test, Z_tv_test, B_spline_test, theta_list, parallel = FALSE, threads = 1L, TestAll = TRUE) {
    .Call(`_surtvep_LogPartialTest`, event, Z_tv, B_spline, event_test, Z_tv_test, B_spline_test, theta_list, parallel, threads, TestAll)
}

VarianceMatrixCalculate <- function(event, Z_tv, B_spline, theta, lambda_i, SmoothMatrix, SplineType = "smooth-spline", method = "Newton", lambda = 1e8, factor = 1.0, parallel = FALSE, threads = 1L) {
    .Call(`_surtvep_VarianceMatrixCalculate`, event, Z_tv, B_spline, theta, lambda_i, SmoothMatrix, SplineType, method, lambda, factor, parallel, threads)
}

VarianceMatrixCalculate_bresties <- function(event, time, Z_tv, B_spline, theta, lambda_i, SmoothMatrix, SplineType = "smooth-spline", method = "Newton", lambda = 1e8, factor = 1.0, parallel = FALSE, threads = 1L) {
    .Call(`_surtvep_VarianceMatrixCalculate_bresties`, event, time, Z_tv, B_spline, theta, lambda_i, SmoothMatrix, SplineType, method, lambda, factor, parallel, threads)
}

surtiver_fixtra_fit_penalizestop_lambdafromlarge <- function(event, count_strata, Z_tv, B_spline, theta_init, Z_ti, beta_ti_init, lambda_spline, SmoothMatrix, effectsize, SplineType = "pspline", method = "Newton", lambda = 1e8, factor = 1.0, parallel = FALSE, threads = 1L, tol = 1e-10, iter_max = 20L, s = 1e-2, t = 0.6, btr = "dynamic", stop = "incre", TIC_prox = FALSE, fixedstep = TRUE, difflambda = FALSE, ICLastOnly = FALSE) {
    .Call(`_surtvep_surtiver_fixtra_fit_penalizestop_lambdafromlarge`, event, count_strata, Z_tv, B_spline, theta_init, Z_ti, beta_ti_init, lambda_spline, SmoothMatrix, effectsize, SplineType, method, lambda, factor, parallel, threads, tol, iter_max, s, t, btr, stop, TIC_prox, fixedstep, difflambda, ICLastOnly)
}

Lambda_estimate_ties2 <- function(knot, delta, z, b_spline, theta, tieseq) {
    .Call(`_surtvep_Lambda_estimate_ties2`, knot, delta, z, b_spline, theta, tieseq)
}

ICcpp <- function(event, Z_tv, B_spline, count_strata, theta, lambda_i, SmoothMatrix, SplineType = "smooth-spline", method = "Newton", lambda = 1e8, factor = 1.0, parallel = FALSE, threads = 1L) {
    .Call(`_surtvep_ICcpp`, event, Z_tv, B_spline, count_strata, theta, lambda_i, SmoothMatrix, SplineType, method, lambda, factor, parallel, threads)
}

ICcpp_bresties <- function(event, time, Z_tv, B_spline, count_strata, theta, lambda_i, SmoothMatrix, SplineType = "smooth-spline", method = "Newton", lambda = 1e8, factor = 1.0, parallel = FALSE, threads = 1L) {
    .Call(`_surtvep_ICcpp_bresties`, event, time, Z_tv, B_spline, count_strata, theta, lambda_i, SmoothMatrix, SplineType, method, lambda, factor, parallel, threads)
}

