name: R-CMD-check

on:
  push:
    branches:
      - main
      - CRAN
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    container: 
      image: rocker/r-ver:4.3.1
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          install2.r --error --deps TRUE remotes
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
          Rscript -e 'install.packages(c("ggplot2", "ggpubr", "RcppArmadillo"))'
      - name: Check package
        run: |
          R CMD build .
          R CMD check *tar.gz --no-manual